const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('kioskElectron', {
  setFullscreen: (on, force) => ipcRenderer.send('set-fullscreen', on, force),
  setKiosk:      (on)       => ipcRenderer.send('set-kiosk',      on),
  sendVirtualKey: (payload) => ipcRenderer.send('virtual-key', payload),
  getVirtualKeyState: () => ipcRenderer.invoke('virtual-key-state'),
  setKeyboardConfig: (config) => ipcRenderer.invoke('keyboard-config', config),
  onWindowState: (cb)       => ipcRenderer.on('window-state', (_, s) => cb(s)),
  hardRefresh:    ()        => ipcRenderer.send('hard-refresh'),
  toggleDevTools: ()        => ipcRenderer.send('toggle-devtools'),
  clearCache:     ()        => ipcRenderer.invoke('clear-cache'),
  wipeData:       (token)   => ipcRenderer.invoke('wipe-data', token),
  getUpdateState: ()        => ipcRenderer.invoke('update-state'),
  checkForUpdate: ()        => ipcRenderer.invoke('update-check'),
  downloadUpdate: ()        => ipcRenderer.invoke('update-download'),
  installUpdate:  ()        => ipcRenderer.invoke('update-install'),
  onUpdateState:  (cb)      => ipcRenderer.on('update-state', (_, state) => cb(state)),
  lockdownWindows: ()       => ipcRenderer.invoke('lockdown-windows'),
  exitApp:        (token)   => ipcRenderer.invoke('exit-app', token),
  setAutoStart:   (enable)  => ipcRenderer.invoke('set-autostart', enable),
  getAutoStart:   ()        => ipcRenderer.invoke('get-autostart'),
  requestAdminToken: ()     => ipcRenderer.invoke('request-admin-token'),
  syncDomains:    (domains, strict) => ipcRenderer.send('sync-domains', domains, strict),
  backupConfig:   (data)    => ipcRenderer.invoke('backup-config', data),
  restoreConfig:  ()        => ipcRenderer.invoke('restore-config'),
  onDomainBlocked: (cb)     => ipcRenderer.on('domain-blocked', (_, host) => cb(host)),
});
